### ISSUE TITLE
readlink -e is not available on macOS

### ISSUE THREAD

**Issue by fletom** [jandelgado/lede-dockerbuilder#1]
the version of `readlink` shipping with macOS doesn't have canonicalization options (`-e` and `-f`), so `./builder.sh` fails with `readlink: illegal option -- e`

I got it to work just fine by removing the call (i.e. `$ROOTFS_OVERLAY` instead of `$(readlink -e $ROOTFS_OVERLAY)`), so it may not actually be necessary

**Comment by jandelgado** [comment]
Unfortunately your fix only works if you use absolute paths for ROOTFS_OVERLAY or OUTPUT_DIR. Docker run does not like relative paths in the volume options. I'll fix the script to not rely on readlink any more.

**Comment by fletom** [comment]
Thanks!
