### ISSUE TITLE
How to bring up menuconfig

### ISSUE THREAD

**Issue by wicadmin** [jandelgado/lede-dockerbuilder#20]
Hi, I would like to select two packages I am building as kernel modules (gobiserial, gobinet). How can get menuconfig to select it?

![image](https://user-images.githubusercontent.com/4563854/93002065-04f31280-f502-11ea-9199-9b128a530467.png)

**Comment by jandelgado** [comment]
AFAIK the [OpenWrt image-builder](https://openwrt.org/docs/guide-user/additional-software/imagebuilder), which is use here, does not provide a menuconfig facility. It operates soley on pre-compiled binaries and profiles.

Have a look at my [lede-dockercompiler](https://github.com/jandelgado/lede-dockercompiler) project for a tool that allows for fully custom images and the use of the menuconfig tool (see usage section for an example).

**Comment by wicadmin** [comment]
Thank you.
