### ISSUE TITLE
bash: ./builder.sh: cannot execute: required file not found 

### ISSUE THREAD

**Issue by GrumpyMeow** [jandelgado/lede-dockerbuilder#37]
I cloned the repo. I tried to start "builder.sh", but i get the error:
```
-bash: ./builder.sh: cannot execute: required file not found
```

this seems to be related to the first line of the script:
```
#!/bin/bash
```
Indeed if i run "/bin/bash" i get an error.

After removing this first line, the builder did work

**Comment by jandelgado** [comment]
On what system are you running the builder? Do you have bash installed? What is the output of ` which bash` ?
