### ISSUE TITLE
Downloading from downloads.openwrt.org slow

### ISSUE THREAD

**Issue by GrumpyMeow** [jandelgado/lede-dockerbuilder#39]
Hi,
The last few months i noticed that the speeds of downloads became much slower.  
I thought that i would be able to improve download speeds by selecting a mirror, so i provided `LEDE_BUILDER_URL` with a mirror url. Unfortunatly the download of packages still uses the "downloads.openwrt.org" and not the mirror.
```
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/releases/23.05.4/targets/ramips/mt7621/packages/Packages.gz
```

Is there an option to also download packages from the mirror?
(i'm using Nix btw)

**Comment by jandelgado** [comment]
Try to create a custon `repositories.conf`  and use this file by setting the `REPOSITORIES_CONF` environment variable to the files location

Look here for an example: https://openwrt.org/docs/guide-user/additional-software/imagebuilder#adding_package_repositories

**Comment by GrumpyMeow** [comment]
Thank you for this suggestion. I eventually found out it was an issue with ipv6.
