### ISSUE TITLE
Docker OpenWrt for S905 on Android Box

### ISSUE THREAD

**Issue by atharmian** [jandelgado/lede-dockerbuilder#4]
Jan,

Great work !

*I am looking to build a cheap media player + small home router combo on a generic Android Box.*

1. Where on OpenWrt 18.06 page can I find the appropriate file for S905 X/W quadcore arm64v8A, for a generic Android Box?

FYI, an Odroid also uses S905 SoC.

Also, how about the correct roofts ?

2. Is there any available Debian OpenWrt image for S905 ?

How about for Alpine base?

3. I am running LibreElec-Kodi on this S905X/W Android Box.

Now LibreElec can run the very elegant Pi-hole.net Docker on top, with DHCP and DNS besides ad blocking, but lacks simple QoS features like,

-streaming Kodi (fed by Ethernet) priority over downloads/torrents by several home devices attached to the Android Box via LibreElec WiFi tether AP,

- anti bloat like LuCI cake-sqm.

So I believe that instead of Pi-hole add-on, I could run a single OpenWrt docker image on LibreElec on this Android Box.

So what QoS packages should I include?

Cheers,

**Comment by jandelgado** [comment]
Hi,

unfortunately, I don't know the mentioned board, but you can find the available OpenWRT targets here: https://downloads.openwrt.org/releases/18.06.0/targets/

Please place any questions regarding OpenWRT on the OpenWRT forums - these are not in the scope of lede-dockerbuilder, which just aims to provide a build environment for OpenWRT images.

regards 
Jan

**Comment by predators46** [comment]
Check website pulpstone.pw ready openwrt s905x
