### ISSUE TITLE
Error while fetching jessie-backports

### ISSUE THREAD

**Issue by FacundoAcevedo** [jandelgado/lede-dockerbuilder#5]
./builder.sh build example-nexx-wt3020.conf --skip-sudo
--- configuration ------------------------------
RELEASE...........: 18.06.2
TARGET............: ramips
SUBTARGET.........: mt7620
PROFILE...........: wt3020-8M
BUILDER_URL.......: https://downloads.openwrt.org/releases/18.06.2/targets/ramips/mt7620/openwrt-imagebuilder-18.06.2-ramips-mt7620.Linux-x86_64.tar.xz
DOCKER_IMAGE_TAG..: openwrt-imagebuilder:18.06.2-ramips-mt7620
OUTPUT_DIR........: /home/blabla/proyectos/lede-dockerbuilder/output
ROOTFS_OVERLAY....: /home/blabla/proyectos/lede-dockerbuilder/rootfs-overlay
------------------------------------------------
building docker image openwrt-imagebuilder:18.06.2-ramips-mt7620 ...
Sending build context to Docker daemon  5.12 kB
Step 1/10 : FROM debian:8
 ---> 7cd9fb1ee74f
Step 2/10 : LABEL maintainer "Jan Delgado <jdelgado@gmx.net>"
 ---> Using cache
 ---> c38b0ba89739
Step 3/10 : RUN echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list     && apt-get update     && apt-get -t jessie-backports install "gosu"     && apt-get install -y --no-install-recommends ca-certificates wget                    subversion build-essential libncurses5-dev zlib1g-dev                   gawk git ccache gettext libssl-dev xsltproc file unzip                   python time     && apt-get autoclean     && apt-get clean     && apt-get autoremove    && rm -rf /var/lib/apt/lists/*
 ---> Running in fb41fd81dbd5
Ign http://ftp.debian.org jessie-backports InRelease
Ign http://deb.debian.org jessie InRelease
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://ftp.debian.org jessie-backports Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Ign http://ftp.debian.org jessie-backports Release
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Get:4 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  
Err http://ftp.debian.org jessie-backports/main amd64 Packages
  404  Not Found [IP: 130.89.148.12 80]
Fetched 10.1 MB in 4s (2286 kB/s)
W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 130.89.148.12 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list     && apt-get update     && apt-get -t jessie-backports install "gosu"     && apt-get install -y --no-install-recommends ca-certificates wget                    subversion build-essential libncurses5-dev zlib1g-dev                   gawk git ccache gettext libssl-dev xsltproc file unzip                   python time     && apt-get autoclean     && apt-get clean     && apt-get autoremove    && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

`

`curl -s -o /dev/null -w "%{http_code}"  http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages `
`404%                 `

**Comment by jandelgado** [comment]
I just switched the base image to Alpine, the problem should disappear
 then. Please check on the  **switch_to_alpine_base** branch if it works for you, I will merge it later.

**Comment by FacundoAcevedo** [comment]
I've switched and ran the same builder.sh command, it worked flawlessly. :+1: 
Thanks :D

`00226536f636f8e337ce25a9ab6bfda7929e4b09ce249a9f52bbd0696129be8d *openwrt-18.06.1-ramips-mt7620-device-wt3020-8m.manifest
cb2d40a33ff73d71f07b7317154b4860bb1046dc5bfd80a397393940aa4fbcfc *openwrt-18.06.1-ramips-mt7620-wt3020-8M-squashfs-factory.bin
7797c801b90c9e2cd091de4108b4429d492608247967d8e469419f85157f2ad2 *openwrt-18.06.1-ramips-mt7620-wt3020-8M-squashfs-sysupgrade.bin`

**Comment by jandelgado** [comment]
excellent, thanks for testing.

fixed with #6
